project:
  name: "demo-ts"
  version: "1.0.0"
  philosophy: "DAAF-BRIK-CircuitalidadDigital"
  genesis_hash: "b2e6540f2c22c952019db495e3afed9b257615bcd7ad8834d77a344cca394bda"
  created_at: "2025-08-24T13:30:37+02:00"
  
principles:
  circuitality: true
  consciousness: true
  thermodynamics: true
  auditability: true
  documentation: true
  
compliance:
  coverage_requirement: 100
  immutability_check: true
  entropy_monitoring: true
  ethical_validation: true
  documentation_completeness: true
