project:
  name: "demo-py"
  version: "1.0.0"
  philosophy: "DAAF-BRIK-CircuitalidadDigital"
  genesis_hash: "19d5d1624693f1557d6e71eea10d6bb23d3cbd35f3296524347e7fe1c75ea7d0"
  created_at: "2025-08-24T13:30:41+02:00"
  
principles:
  circuitality: true
  consciousness: true
  thermodynamics: true
  auditability: true
  documentation: true
  
compliance:
  coverage_requirement: 100
  immutability_check: true
  entropy_monitoring: true
  ethical_validation: true
  documentation_completeness: true
