name: brik-py
on: [push, pull_request]
jobs:
  py-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: demo-py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Coverage 100% (global + per-file, branches)
        working-directory: demo-py
        run: ./scripts/test-coverage.sh
