name: brik-py
on: [push, pull_request]
jobs:
  py-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        working-directory: demo-py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Coverage 100% (global + per-file, branches)
        working-directory: demo-py
        run: |
          ./scripts/test-coverage.sh
          pytest --cov=src --cov-branch --cov-report=xml
      - name: BRIK Certification Hash (strict docs)
        working-directory: demo-py
        run: STRICT_DOCS=1 ./scripts/brik-certify.sh
      - name: Upload BRIK cert artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-py-brik-cert
          path: |
            demo-py/.brik-cert.json
            demo-py/.brik-cert.sha256
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: demo-py
          fail_ci_if_error: true
