name: brik-rust
on: [push, pull_request]
jobs:
  rust-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Coverage 100% (lines+branches)
        working-directory: demo-brik
        run: |
          ./scripts/test-coverage.sh
          cargo tarpaulin --workspace --ignore-tests --branch --out Xml --output-dir target/tarpaulin
      - name: BRIK Certification Hash (strict docs)
        working-directory: demo-brik
        run: STRICT_DOCS=1 ./scripts/brik-certify.sh
      - name: Upload BRIK cert artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-brik-brik-cert
          path: |
            demo-brik/.brik-cert.json
            demo-brik/.brik-cert.sha256
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: demo-brik/target/tarpaulin
          fail_ci_if_error: true
